# Generated by Django 5.2.10 on 2026-05-08 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
